name: DRF Test

on:
  push:
  workflow_call:

jobs:
  lint:
    name: black check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install black
        run: pip install black
      - name: check black
        run: black --check .

  drf-test:
    needs: lint
    name: test drf with docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set env file
        run: |
          cat <<EOF > .env
          # DB
          POSTGRES_DB=postgres
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_PORT=5432
          # DRF
          DB_HOST=db
          DJANGO_SECRET_KEY=just_test_secret_885f6d0c189dd4ccd619820b9f28f56bbe02be48d978f
          RUN_MODE=local
          DJANGO_ALLOWED_HOST=localhost
          # NCP
          NCP_ACCESS_KEY=${{ secrets.NCP_ACCESS_KEY }}
          NCP_SECRET_KEY=${{ secrets.NCP_SECRET_KEY }}
          EOF

      - name: test
        run: |
          docker compose up --build -d
          docker compose run follow-app python manage.py test
